### ISSUE TITLE
automatic copy of a data file when it is closed (time or size limit overdue)

### ISSUE THREAD

**Issue by Bob690608** [jay1han/V2-Documents#3]
Each time a data file is finished, tha actiserver should call a script to trigger the saving of a copy in the backup storage computer, this way the rsync from the actiserver will only save the current file, the previous ones will already be on the backup).

**Comment by jay1han** [comment]
Configuration option SYNC_EXEC specifies the full path of the script. If empty, no script will be run, with the risk of storage overflow. The script is called with the file name (not full path) of the file to sync.
Note: configuration option REPO_ROOT contains the path of the CSV files (default /media/actimetre).
Note: another configuration option, CLEANUP_EXEC, specifies the path to a script that is called when remaining disk space falls below 10%
Note: if, despite all this, remaining disk space falls below 5%, Actiserver will start erasing files by itself.

**Comment by jay1han** [comment]
This issue is obsoleted by #15
