### ISSUE TITLE
group datafiles in a subdirectory named after the project file

### ISSUE THREAD

**Issue by Bob690608** [jay1han/V2-Documents#6]
Will help sorting datafiles

**Comment by Bob690608** [comment]
- no risk to forget some datafiles in a given project
- datafiles unaffected (not normal) will appear at the root level
- the insertion of an actimeter in a project (or the removal from a project) will be a companion task to the management of mice cages

**Comment by Bob690608** [comment]
eventually, when an actimeter is awakened after a time of inactivity (to be set in the anvironment variables), an alert is triggered on the dashboard to ask for the reassignation of the actimeter to the previous project

**Comment by jay1han** [comment]
Need to refine the idea based on ultimate objective of this change.
Questions
- What if a project name changes
- What if the project name contains unacceptable characters for file path
- What is a good default for the time of inactivity

Alternate proposal: assign cage ID to sensor ID, then link cage ID to project. The CSV files will be stored in subfolders named after the cage ID. This assumes that there is a standard system for identifying cages. If there isn't please invent one.

**Comment by jay1han** [comment]
This issue is obsoleted by #11

**Comment by jay1han** [comment]
Consensus is to use the project ID (a number) as the folder name
